version: "3.8"

volumes:
  warenkorb_mysql:

networks:
  database:
  backend:
  frontend:

services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
      target: cli
      args:
        PHP_VERSION: '8.2'
    volumes:
      - './:/code'
    networks:
      - backend
      - database
    profiles:
      - tools

  fpm:
    build:
      dockerfile: Dockerfile
      context: .
      target: fpm
      args:
        PHP_VERSION: '8.2'
    volumes:
      - './:/code'
    networks:
      - backend
      - database

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/etc/certs:/etc/nginx/ssl
    networks:
      - backend
      - frontend

  database:
    image: mariadb:10
    environment:
      MARIADB_DATABASE: ${DATABASE_DBNAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASS}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
    volumes:
      - warenkorb_mysql:/var/lib/mysql
    networks:
      - database